# Generated by Django 3.2.16 on 2022-12-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='des',
            new_name='inform',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='pname',
            new_name='name',
        ),
    ]
