# Generated by Django 3.2.16 on 2022-12-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_auto_20221230_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('cname', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
